baseURL = "https://gungorbasa.com/"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 26
title = "Gungor Basa"

[pagination]
  pagerSize = 10

[permalinks]
  posts = "/:contentbasename"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changeFreq = "weekly"
  priority = 0.5

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
